import os

readme_content = r"""# Visualcheme Chemical Engineering Skills & Unit Design Knowledge Base

This knowledge repository compiles fundamental engineering principles, governing mathematical formulations, design procedures, heuristics, and extracted figures from *Chemical Engineering Design: Principles, Practice and Economics of Plant and Process Design* (2nd Edition, Gavin Towler & Ray Sinnott).

It serves as an expert on-demand skill library for LLMs and autonomous agents designing, modeling, simulating, and visualizing chemical process unit operations in **Visualcheme**.

---

## Skill Directory Index (Fully Verified Against Towler & Sinnott, 2nd Edition)

| Skill Name | Reference Chapter | Primary Focus & Unit Operations | Key Verified Figures & Nomographs | Key Verified Equations |
| :--- | :--- | :--- | :--- | :--- |
| **[`che-utilities-pinch`](./che-utilities-pinch/SKILL.md)** | **Chapter 3** (pp. 114–169) | Utilities (Steam, Cooling Water, Refrigeration, Cogeneration), Energy Recovery, Pinch Analysis, Composite Curves, Grand Composite Curve, Heat Exchanger Network (HEN) Synthesis. | Cogeneration cycle (3.1), Steam headers (3.2), Cooling tower (3.3), Psychrometric chart (3.4), Refrigeration cycle (3.5), Flue gas heat recovery (3.12), Composite curves (3.14, 3.15), Grand Composite Curve (3.17, 3.18), HEN Grid diagram (3.20), Pinch matching rules (3.21), Capital-energy tradeoff (3.26), Distillation column integration (3.28). | Steam price (3.1), Refrigeration COP (3.2), Carnot COP (3.3). |
| **[`che-process-simulation`](./che-process-simulation/SKILL.md)** | **Chapter 4** (pp. 172–242) | Flowsheet simulation architectures (Sequential Modular vs Equation-Oriented), Thermodynamic model selection decision trees (EOS vs Activity Models), Flash calculations (Rachford-Rice algorithm), Recycle tear stream convergence (Wegstein). | SM vs EO comparison (4.1), Information flow (4.2), Master thermodynamic selection trees (4.4, 4.5, 4.6), Flash drum model (4.7), Wegstein acceleration (4.23). | Rachford-Rice objective function (4.7), Wegstein secant slope & weighting factors (4.15, 4.21). |
| **[`che-instrumentation-control`](./che-instrumentation-control/SKILL.md)** | **Chapter 5** (pp. 262–285) & **Sec 20.11** | Piping & Instrumentation Diagrams (P&IDs, ISA symbology), Feedback loops, Cascade control, Ratio control, Override control, Split-range control, Feedforward control, Valve inherent characteristics (Linear, Equal %, Quick Opening), Column & reactor control schemes. | P&ID symbols (5.1), Valve failure positions (5.2), Feedback loops (5.4), Cascade control (5.5, 5.6), Ratio control (5.7), Override control (5.8), Split-range control (5.9), Feedforward control (5.10), Valve characteristics (5.11), Distillation column control (5.12), Reactor control (5.13). | Control valve liquid ($C_v$, 20.31) and gas sizing (20.32). |
| **[`che-equipment-specification`](./che-equipment-specification/SKILL.md)** | **Chapter 13** (pp. 566–571) | Equipment selection workflow (Proprietary vs Non-Proprietary), Master equipment selection guide (Table 13.1), Separation processes guide (Table 13.2), Standard design margins / overdesign factors (pumps, columns, exchangers, vessels), Procurement data sheets. | Equipment Selection Guide (Table 13.1), Separation Processes Guide (Table 13.2). | Standard overdesign factors (+10% to +25%). |
| **[`che-reactors-mixers`](./che-reactors-mixers/SKILL.md)** | **Chapter 15** (pp. 640–758) | Reactor sizing (Batch, CSTR, PFR, Catalytic Fixed Bed), Residence time $\tau$, Damköhler number $Da$, Stirred vessel geometry ($H/D$, baffles), Impeller selection (Propeller, Rushton turbine, Pitched blade, Anchor), Power curves ($N_P$ vs $Re$), Thermal management (Jackets, Coils, Runaway prevention). | Reactor procedure (15.1), Tank dimensions (15.7), Impeller types (15.12, 15.13), Agitator selection guide (15.14), Propeller power curves (15.15), Turbine power curves (15.16), Heating & cooling arrangements (15.20), Fixed bed catalytic reactor (15.25), Bed support internals (15.28). | Batch time (15.1), CSTR volume (15.3), PFR volume (15.5), Arrhenius kinetics (15.11), Agitation Reynolds number (15.12), Power number (15.14). |
| **[`che-fluid-separators`](./che-fluid-separators/SKILL.md)** | **Chapter 16** (pp. 762–814) | Gas-liquid separators (Vertical knock-out pots, Horizontal flash drums), Souders-Brown terminal vapor velocity $u_v$, Wire mesh demister pads, Liquid surge holdup heuristics, Liquid-liquid gravity decanters (Stokes droplet settling, weir hydraulics). | Vertical separator with demister (16.11), Horizontal separator with boot (16.12), Vertical decanter (16.13), Horizontal decanter (16.14), Decanter with recycle (16.15), Coalescing filter (16.16). | Souders-Brown terminal settling velocity (16.5) and maximum vapor velocity (16.6), Hydrostatic decanter interface & weir balances (16.9, 16.10, 16.11). |
| **[`che-distillation-columns`](./che-distillation-columns/SKILL.md)** | **Chapter 17** (pp. 816–941) | Continuous distillation anatomy, Rigorous stage MESH equations, McCabe-Thiele graphical method (ROL, SOL, $q$-line, $R_{min}$, $N_{min}$), Fenske-Underwood-Gilliland (FUG) shortcut rating, Tray hydraulics (Sieve, Valve, Bubble-cap, Fair's flooding, weeping, total pressure drop, downcomer backup choke), Packed columns (GPDC, HETP). | Column system layout (17.1), Stage MESH balances (17.2), McCabe-Thiele construction (17.5), Total reflux (17.6), Minimum reflux (17.7), Gilliland correlation (17.18), Tray liquid cross-flow (17.23), Sieve plate (17.24), Valve plate (17.26), Hydraulic limits envelope (17.33), Fair's flooding correlation (17.34), Weeping correlation (17.37), Downcomer backup levels (17.43), Random packings (17.46), Structured packing (17.47), GPDC correlation (17.54). | Stage MESH equations (17.1–17.4), Fenske minimum stages (17.8), Underwood minimum reflux (17.9, 17.10), McCabe-Thiele lines (17.12, 17.14, 17.16, 17.17), Gilliland stages (17.18a), Column diameter (17.36), Flow parameter $F_{LV}$ (17.45), Fair's flooding velocity (17.47), Weeping velocity (17.48), Dry plate drop (17.49), Downcomer backup (17.55). |
| **[`che-solids-handling`](./che-solids-handling/SKILL.md)** | **Chapter 18** (pp. 946–1054) | Particulate characterization (Sauter mean $d_{32}$), Fluidization (Ergun equation, minimum fluidization velocity $U_{mf}$), Stairmand standard gas cyclones (High-efficiency and High-throughput designs, cut diameter scaling, pressure drop), Hydrocyclones (Zanker method), Cake filtration (Ruth equation, rotary vacuum drum filters), Industrial drying (Rotary, Fluidized bed, Spray dryers). | Reverse-flow cyclone schematic (18.31), Standard Stairmand dimensions (18.32), Stairmand performance curves (18.33), Scale-up transposition (18.34), Cyclone pressure drop factor (18.35), Rotary drum filter (18.49), Hydrocyclone assembly (18.54), Zanker hydrocyclone nomograph (18.56), Standard hydrocyclone geometry (18.57), Direct-heat rotary dryer (18.60), Fluidized-bed dryer (18.62), Spray dryer (18.65). | Sauter mean diameter (18.1), Fluidization pressure drop (18.14), Ergun minimum fluidization velocity (18.15, 18.16, 18.17), Stairmand cut diameter scaling (18.23), Stairmand pressure drop (18.24), Zanker hydrocyclone cut diameter (18.27) and efficiency (18.28), Ruth filtration equations (18.29, 18.30). |
| **[`che-heat-exchangers`](./che-heat-exchangers/SKILL.md)** | **Chapter 19** (pp. 1056–1210) | Shell-and-tube exchangers (TEMA classifications, tube layout, pitch), Thermal sizing ($Q = U_o A_o \Delta T_{lm} F_T$), Tube-side rating (Sieder-Tate, tube pressure drop), Kern's shortcut rating (shell equivalent diameter $d_e$, cross-flow area $A_s$, shell heat transfer and pressure drop), Bell-Delaware rigorous method (Tinker stream flows A, B, C, E, F), Reboilers (Kettle, Thermosiphon, burnout flux), Condensers, Plate heat exchangers. | TEMA Fixed tubesheet BEM (19.3), U-tube BEU (19.4), Pull-through AET (19.5), Split-backing ring AES (19.6), Kettle reboiler AKU (19.8), Segmental baffle geometry (19.14), Temperature profiles (19.18), $F_T$ charts (19.19, 19.20), Tube-side $j_h$ factor (19.23) and friction factor (19.24), Bell-Delaware stream analysis (19.26), Kern shell-side $j_h$ factor (19.29) and friction factor (19.30), Design flowchart (19.31), Forced circulation reboiler (19.46), Thermosiphon reboiler (19.47), Kettle reboiler (19.48), Plate exchanger assembly (19.56) and flow patterns (19.58). | Overall heat transfer (19.1), Overall coefficient $U_o$ with fouling (19.2), Tube count & bundle diameter (19.3a, 19.3b), LMTD (19.4), Dimensionless $R$ and $S$ (19.7, 19.8), Tube-side Sieder-Tate Nusselt (19.10), Tube pressure drop (19.11), Tube $j_h$ (19.15), Kern shell equivalent diameter (19.16), Shell cross-flow area (19.17), Shell heat transfer coefficient (19.18), Shell pressure drop (19.19, 19.20), Nucleate pool boiling (19.41), Critical burnout heat flux (19.42). |
| **[`che-fluid-transport-piping`](./che-fluid-transport-piping/SKILL.md)** | **Chapter 20** (pp. 1216–1272) | Pipeline fluid dynamics, Darcy-Weisbach frictional pressure drop, Hagen-Poiseuille laminar flow, Colebrook-White and Churchill turbulent friction factors, Minor losses in fittings/valves, Economic pipe diameter selection, Centrifugal pumps ($H-Q$ curves, operating point, NPSHa, cavitation prevention, mechanical seals), Multi-stage gas compression with intercooling, Control valve $C_v$ sizing. | Compressor selection guide (20.1), Pump selection guide (20.3), Pipe friction factor chart (20.5), Industrial valve types (20.6), Multistage compressor curves with intercooling (20.11), Centrifugal pump anatomy (20.12), Pipeline system schematic (20.13), Pump characteristic curves (20.15), System head curve and operating point (20.16), Mechanical seal (20.20), Economic pipe diameter nomograph (20.21). | Darcy-Weisbach pressure drop (20.1), Hagen-Poiseuille laminar friction (20.2), Colebrook-White implicit correlation (20.3), Churchill universal explicit friction factor (20.4), Polytropic gas compression (20.5, 20.10), Equal stage pressure ratio for intercooled compressors (20.11), System head curve (20.12, 20.13), NPSH available (20.15), Economic pipe diameter (20.24, 20.25), Control valve gas sizing (20.32). |

---

## How to Use in Visualcheme Development
1. **Mathematical Model Formulation**: Reference the governing equations in the relevant unit skill (e.g. Darcy-Weisbach for pipes, MESH equations for distillation, LMTD/Kern for heat exchangers, Souders-Brown for separators, Stairmand equations for cyclones, Ruth equation for filtration).
2. **Visual & Didactic Gradient Selection**: Use the physical state variables and limits documented in each skill to populate Visualcheme's user gradient selector (e.g., pressure drop profiles, velocity fields, Fair's percent flooding, NPSH cavitation margins, exergy loss, shear stress).
3. **Preset Scenario Calibration**: Use the design margins and heuristics tables to set realistic default dimensions, flows, and operating pressures for demonstration cases.
"""

with open('.agents/skills/README.md', 'w', encoding='utf-8') as f:
    f.write(readme_content)
print(".agents/skills/README.md updated successfully!")
